### ISSUE TITLE
about training and test

### ISSUE THREAD

**Issue by vincennnnt** [songdejia/siamese-RPN-pytorch#1]
Sorry to bother u,but i have some questions about  the implementation of  SiamRPN.When i use   zkisthebest's code,the performance is so bad ,so i tried to add ur code into his,but when i train the code,it alerts the error **TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'PIL.Image.Image'>**.So i wonder whether u  can provide **train.py** and **test.py**

**Comment by songdejia** [comment]
Thanks for your attention. Now this work is not yet  complete, some parts need to be modified and tested. I will update later, please pay attention to this work.

**Comment by vincennnnt** [comment]
@songdejia Thank u so much！！！

**Comment by songdejia** [comment]
We have just finished v1.0 on pytorch and tensorflow.  
pytorch-version is available here [https://github.com/songdejia/siamese-RPN]
tensorflow-version is available here [https://github.com/makalo/Siamese-RPN-tensorflow.git]
@vincennnnt

**Comment by vincennnnt** [comment]
@

**Comment by vincennnnt** [comment]
@songdejia Thank u for ur great job！！
